export const routes = {
  HOMESCREENS: 'HOMESCREENS',
  TENDENCYSCREENS: 'TENDENCYSCREENS',
  DISCOVERSCREENS: 'DISCOVERSCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  PROFILESCREENS: 'PROFILESCREENS',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
};
