export const routes = {
  HOMESCREENS: 'HOMESCREENS',
  TENDENCYSCREENS: 'TENDENCYSCREENS',
  DISCOVERSCREENS: 'DISCOVERSCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  PROFILESCREENS: 'PROFILESCREENS',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
  PROFILEDETAILS: 'PROFILEDETAILS',
  LOGINSCREERN: 'LOGINSCREERN',
  SIGNUPSCREEN: 'SIGNUPSCREEN',
  ALLNEWSSCREEN: 'ALLNEWSSCREEN',
  SYSTEMNEWS: 'SYSTEMNEWS',
};
